version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Local development tools
  tfsec:
    image: aquasec/tfsec:latest
    volumes:
      - .:/src
    working_dir: /src
    command: [".", "--format", "table"]
    profiles:
      - tools

  trivy:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src
    working_dir: /src
    command: ["image", "--severity", "HIGH,CRITICAL", "devopsasg1-app:latest"]
    profiles:
      - tools

networks:
  default:
    name: devopsasg1-network
